train_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/train_corners
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      compose:
        type: RandomOrder
        transforms:
          rnd_perspective:
            type: RandomPerspective
            params:
              distortion_scale: 0.2
              p: 0.5
          color_jitter:
            type: ColorJitter
            params:
              brightness: [0.6, 1.4]
              contrast: [0.6, 1.4]
              saturation: [0.6, 1.4]
              hue: [-0.02, 0.02]
          hflip:
            type: RandomHorizontalFlip
          affine:
            type: RandomAffine
            params:
              degrees: 10
              shear: [-2, 2]
              translate: [0.05, 0.05]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: True

projection_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/train_crop
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 4
  shuffle: False

test_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/test_full
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: False
