top_arch:
  module: cabrnet.protopnet.model
  name: ProtoPNet

extractor: # How to build the feature extractor
  backbone:
    arch: vgg19
    layer: features
    weights: IMAGENET1K_V1 # or null, or path/to/state.pth
  add_on:
    init_mode: PROTOPNET
    conv1:
      type: Conv2d
      params:
        out_channels: 128
        kernel_size: 1
        bias: True
    act1:
      type: ReLU
    conv2:
      type: Conv2d
      params:
        out_channels: 128
        kernel_size: 1
        bias: True
    act2:
      type: Sigmoid

classifier:
  module: cabrnet.protopnet.decision
  name: ProtoPNetClassifier
  params:
    num_classes: 200
    num_proto_per_class: 10
    #prototype_activation: log
    proto_init_mode: UNIFORM
    compatibility_mode: True
