top_arch: # Optional
  module: cabrnet.prototree.model
  name: ProtoTree # Take "extractor" and "classifier", implement the generic class ProtoClassifier

extractor: # How to build the feature extractor
  backbone:
    arch: resnet50
    layer: layer4
    weights: IMAGENET1K_V1
  add_on:
    init_mode: XAVIER
    conv1:
      type: Conv2d # nn.Module name
      params:
        out_channels: 128
        kernel_size: 1
        bias: False
    sigmoid1:
      type: Sigmoid

similarity:
  name: LegacyProtoTreeSimilarity

classifier: # How to compute the decision from the features
  module: cabrnet.prototree.decision
  name: ProtoTreeClassifier
  params:
    num_features: 128
    num_classes: 196
    depth: 9
    leaves_init_mode: ZEROS
    proto_init_mode: SHIFTED_NORMAL
    log_probabilities: False
