#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -e

echo -e "\e[1;33m Formatting before commit\e[1;0m"
test -d ".venv" || echo "WARNING: python dependencies should be located in .venv\nCheck installation instructions"
export PATH="$PATH:$PWD/.venv/bin:$PWD/venv/bin"
black --version
isort --version-number

black src tools tests
isort src tools tests
