# Prototype for CaBRNet CI

#variables:
#  CABRNET_VERSION: "0.2"
#  TAG: "2.0"

#default:
#  interruptible: true
#  tags: [ nix-v2 ] 

#stages:
#  - typing # in charge of typechecking using mypy
#  - test # in charge of running unit tests
#  - docstrings # in charge of ensuring the correct style of docstrings
#  - doc # in charge of building the doc
#  - install # in charge of checking that the soft can be released proper
#  - mirror # in charge of replicating the state of this repo on others
