# Prototype for CaBRNet CI

variables:
  CABRNET_VERSION: "0.2"
  TAG: "0.2"

default:
  interruptible: true
  tags: [ pub-nix ]

stages:
  - dependencies # in charge of downloading the correct set of dependencies
  - build # in charge of running the proper setup tool to build the archive
  - formatting # in charge of ensuring the correct style of docstrings and code
  - typing # in charge of typechecking using mypy
#  - test # in charge of running unit tests
#  - doc # in charge of building the doc
#  - install # in charge of checking that the soft can be released proper
#  - mirror # in charge of replicating the state of this repo on others

dependencies:
  stage : dependencies
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --command python3 -m pip install -r requirements.txt

build:
  stage : build
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --command ci/install_and_build.sh

code:
  stage : formatting
  allow_failure: true
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --command ci/formatting.sh

docstrings:
  stage : formatting
  allow_failure: true
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --command ci/docstring_check.sh

typing:
  stage : typing
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --command ci/typecheck.sh
