name: cabrnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch~=2.1.0
  - torchvision~=0.16.0
  - captum~=0.7.0
  - numpy>=1.19.5
  - pillow==9.0.0
  - setuptools~=60.2.0
  - tqdm~=4.62.3
  - pyyaml~=6.0.1
  - loguru~=0.7.2
  - zenodo_get~=1.5.1
  - python-graphviz
  - pip
  - pip:
      - opencv-python-headless
