site_name: CaBRNet documentation
repo_url: https://git.frama-c.com/pub/cabrnet
repo_name: GitLab
docs_dir: docs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - .js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js