train_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/train_crop_augmented
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: True

projection_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/train_crop
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: False

test_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/CUB_200_2011/dataset/test_crop
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: False
