param_groups:
  backbone: extractor.convnet
  addons: extractor.add_on
  prototypes: classifier.prototypes
  last_layer: classifier.last_layer

optimizers:
  # Optimizer used during the first epochs
  warmup_optimizer:
    type: Adam
    groups:
      addons:
        lr: 0.003
        weight_decay: 0.001
      prototypes:
        lr: 0.003

  # Main optimizer
  joint_optimizer:
    type: Adam
    groups:
      backbone:
        lr: 0.0001
        weight_decay: 0.001
      addons:
        lr: 0.003
        weight_decay: 0.001
      prototypes:
        lr: 0.003
    scheduler:
      type: StepLR
      params:
        step_size: 5
        gamma: 0.1

  # Optimizer used during the first epochs
  last_layer_optimizer:
    type: Adam
    groups:
      last_layer:
        lr: 0.0001

num_epochs: 10

periods:
  warmup:
    epoch_range: [ 0, 4 ]
    freeze: [ backbone ]
    optimizers: warmup_optimizer
  main_training:
    epoch_range: [ 5, 7 ]
    freeze: last_layer
    optimizers: joint_optimizer
  fine_tuning:
    epoch_range: [ 8, 9 ]
    freeze: [ backbone, addons, prototypes ]
    optimizers: last_layer_optimizer
