import torch
from torch import nn
from torchaudio.transforms import FrequencyMasking, TimeMasking

__all__ = ["FrequencyMasking", "TimeMasking", "BrownNoise"]


class BrownNoiseBank(nn.Module):
    """
    Pre-computes a bank of brown noise STFTs.
    Brown noise is generated by cumulative sum of white noise (1/f² PSD).

    Args:
        cfg:        SpecImgConfig — all STFT parameters are derived from it.
                    win_length is set to n_fft.
        bank_size:  Number of distinct noise samples to pre-compute.
    """

    def __init__(
        self,
        n_fft: int,
        width: int,
        window: str = "hann_window",
        bank_size: int = 256,
    ):
        super().__init__()

        self.n_fft = n_fft
        self.width = width
        window_fn = getattr(torch, window, torch.hann_window)
        # Signal length: enough samples to cover expected_length frames
        bank = self._build_bank(bank_size, 200, window_fn(n_fft))
        self.bank_size = bank_size
        self.register_buffer("bank", bank)  # [bank_size, freq_bins, time_frames]

    def _brown_noise(self, length: int) -> torch.Tensor:
        """Cumsum of white noise → 1/f² power spectrum."""
        b = torch.cumsum(torch.randn(length), dim=0)
        return b / b.std()

    @torch.no_grad()
    def _build_bank(self, bank_size: int, hop_length: int, window: torch.Tensor) -> torch.Tensor:
        samples = []
        total_length = (self.width - 1) * hop_length
        for _ in range(bank_size):
            stft = torch.stft(
                self._brown_noise(total_length),
                n_fft=self.n_fft,
                hop_length=hop_length,
                win_length=self.n_fft,
                window=window,
                return_complex=True,
                center=True,
            )
            samples.append(stft)
        return torch.stack(samples)  # [bank_size, F, T]

    def forward(self, coefficients: torch.Tensor) -> torch.Tensor:
        """
        Draw a random noise STFT.
        Input contains the amplitude of the noise for each element in the batch

        Returns:
            Complex tensor of shape [batch, freq_bins, n_frames].
        """
        assert coefficients.ndim == 1
        b = coefficients.shape[0]
        indices = torch.randint(
            low=0,
            high=self.bank_size,
            size=(b,),
            device=self.bank.device,  # type: ignore
        )
        noise = self.bank[indices]  # type: ignore
        return noise * coefficients.reshape(b, 1, 1)


class BrownNoise(nn.Module):
    """
    Adds brown noise to complex STFT tensors at a given SNR.

    Args:
        cfg:       SpecImgConfig.
        noise_ratio:    noise_ratio to apply
        bank_size: Number of noise samples to pre-compute.
    """

    def __init__(
        self,
        n_fft: int,
        width: int,
        *,
        window: str = "hann_window",
        noise_ratio: float | tuple[float, float] = 0.1,
        bank_size: int = 256,
    ):
        super().__init__()
        self.noise_ratio = noise_ratio
        self.noise_bank = BrownNoiseBank(
            n_fft=n_fft,
            width=width,
            window=window,
            bank_size=bank_size,
        )

    def forward(self, stft: torch.Tensor) -> torch.Tensor:
        """
        Args:
            stft: Complex tensor [batch, freq_bins, time_frames].

        Returns:
            Noisy STFT, same shape and dtype as input.
        """
        if not torch.is_complex(stft):
            raise ValueError("Input must be a complex STFT tensor.")

        b, _f, _t = stft.shape

        noise_std = stft.abs().pow(2).mean().sqrt() * self.noise_ratio
        noise = self.noise_bank.forward(noise_std)
        return stft + noise
