top_arch:
  module: cabrnet.prototree.model
  name: ProtoTree

extractor:
  backbone:
    arch: resnet18
    layer: layer4
    weights: IMAGENET1K_V1
  add_on:
    init_mode: XAVIER
    conv1:
      type: Conv2d
      params:
        out_channels: 128
        kernel_size: 1
        bias: False
    sigmoid1:
      type: Sigmoid

classifier:
  module: cabrnet.prototree.decision
  name: ProtoTreeClassifier
  params:
    num_features: 128
    num_classes: 10
    depth: 4
    leaves_init_mode: ZEROS
    proto_init_mode: SHIFTED_NORMAL
    log_probabilities: False
