# train_set:
#   module: torchvision.datasets.stanford_cars # Module name
#   name: StanfordCars # Class name
#   params: # How to initialize the dataset
#     root: data
#     split: train
#     transform:
#       resize:
#         type: Resize
#         params:
#           size: [256, 256]
#       random_order:
#         type: RandomOrder
#         transforms:
#           rnd_perspective:
#             type: RandomPerspective
#             params:
#               distortion_scale: 0.5
#               p: 0.5
#           color_jitter:
#             type: ColorJitter
#             params:
#               brightness: [0.6, 1.4]
#               contrast: [0.6, 1.4]
#               saturation: [0.6, 1.4]
#               hue: [-0.4, 0.4]
#           hflip:
#             module: torchvision.transforms # Optional [by default, will call torchvision]
#             type: RandomHorizontalFlip
#           affine:
#             type: RandomAffine
#             params:
#               degrees: 15
#               shear: [-2, 2]
#       rnd_crop:
#         type: RandomCrop
#         params:
#           size: [224, 224]
#       to_tensor:
#         type: ToTensor
#       normalize:
#         type: Normalize
#         params:
#           mean: [0.485, 0.456, 0.406]
#           std: [0.229, 0.224, 0.225]
#   batch_size: 64
#   shuffle: True
#   num_workers: 6

# projection_set:
#   module: torchvision.datasets.stanford_cars
#   name: StanfordCars
#   params:
#     root: data/
#     split: train
#     transform:
#       resize:
#         type: Resize
#         params:
#           size: [224, 224]
#       to_tensor:
#         type: ToTensor
#       normalize:
#         type: Normalize
#         params:
#           mean: [0.485, 0.456, 0.406]
#           std: [0.229, 0.224, 0.225]
#   batch_size: 64
#   shuffle: False
#   num_workers: 6

# test_set:
#   module: torchvision.datasets.stanford_cars
#   name: StanfordCars
#   params:
#     root: data
#     split: train
#     transform:
#       resize:
#         type: Resize
#         params:
#           size: [224, 224]
#       to_tensor:
#         type: ToTensor
#       normalize:
#         type: Normalize
#         params:
#           mean: [0.485, 0.456, 0.406]
#           std: [0.229, 0.224, 0.225]
#   batch_size: 64
#   shuffle: False
#   num_workers: 6

train_set:
  # module: torchvision.datasets.stanford_cars # The dataset used to be available here
  module: torchvision.datasets # Module name
  name: ImageFolder # Class name
  params: # How to initialize the dataset
    root: data/cars/dataset/train
    transform:
      resize:
        type: Resize
        params:
          size: [256, 256]
      random_order:
        type: RandomOrder
        transforms:
          rnd_perspective:
            type: RandomPerspective
            params:
              distortion_scale: 0.5
              p: 0.5
          color_jitter:
            type: ColorJitter
            params:
              brightness: [0.6, 1.4]
              contrast: [0.6, 1.4]
              saturation: [0.6, 1.4]
              hue: [-0.4, 0.4]
          hflip:
            module: torchvision.transforms # Optional [by default, will call torchvision]
            type: RandomHorizontalFlip
          affine:
            type: RandomAffine
            params:
              degrees: 15
              shear: [-2, 2]
      rnd_crop:
        type: RandomCrop
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: True
  num_workers: 6


projection_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/cars/dataset/train
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: False
  num_workers: 6


test_set:
  module: torchvision.datasets
  name: ImageFolder
  params:
    root: data/cars/dataset/test
    transform:
      resize:
        type: Resize
        params:
          size: [224, 224]
      to_tensor:
        type: ToTensor
      normalize:
        type: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  batch_size: 16
  shuffle: False
  num_workers: 6
