top_arch:
  module: cabrnet.archs.protopool.model
  name: ProtoPool

extractor:
  backbone:
    arch: resnet18
    layer: layer4
    weights: IMAGENET1K_V1
  add_on:
    init_mode: XAVIER
    conv1:
      type: Conv2d
      params:
        out_channels: 256
        kernel_size: 1
        bias: False
    sigmoid1:
      type: Sigmoid

similarity:
  name: LegacyProtoPNetSimilarity

classifier:
  module: cabrnet.archs.protopool.decision
  name: ProtoPoolClassifier
  params:
    num_classes: 10
    num_prototypes: 30
    num_slots_per_class: 5
    proto_init_mode: UNIFORM
    compatibility_mode: True

